### ISSUE TITLE
feat: ephemeral pages

### ISSUE THREAD

**Issue by ijo42** [MrZillaGold/discord.js-pages#509]
i suggest to add build-method option, creating ephemeral message instead of publicly visible list

**Comment by MrZillaGold** [comment]
Разве к ним можно цеплять кнопки и бот будет видеть взаимодействие?

**Comment by ijo42** [comment]
Точно можно подписываться через interactionCreate, через channel-collector не уверен

**Comment by MrZillaGold** [comment]
https://github.com/MrZillaGold/discord.js-pages/releases/tag/1.4.2

```js
.build({
   ephemeral: true
});
```
